# --- Configurazione Database PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/moneymind
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configurazione JPA / Hibernate ---
# 'update': crea le tabelle se non esistono, o le aggiorna se cambi il codice.
# È perfetto per lo sviluppo. (Non cancella i dati).
spring.jpa.hibernate.ddl-auto=update

# Dice a Hibernate quale dialetto SQL usare per le query
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Debugging (Utilissimo per l'esame) ---
# Mostra nella console le query SQL che Spring sta facendo
spring.jpa.show-sql=true
# Formatta l'SQL per renderlo leggibile
spring.jpa.properties.hibernate.format_sql=true
